### ISSUE TITLE
Class 'SoapClient' not found 

### ISSUE THREAD

**Issue by geniuskidkanyi** [cwispy/ispcfg3#26]
am getting this error, what my be the problem
`Error: Error: Class 'SoapClient' not found in /var/www/clients/client0/web1/web/modules/servers/ispcfg3/ispcfg3.php:243 Stack trace: #0 /var/www/clients/client0/web1/web/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): ispcfg3_CreateAccount(Array) #1 /var/www/clients/client0/web1/web/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->call('CreateAccount', Array) #2 /var/www/clients/client0/web1/web/includes/modulefunctions.php(0): WHMCS\Module\Server->call('CreateAccount', Array) #3 /var/www/clients/client0/web1/web/includes/modulefunctions.php(0): ModuleCallFunction('Create', 8, Array, 0) #4 /var/www/clients/client0/web1/web/includes/orderfunctions.php(0): ServerCreateAccount(8) #5 /var/www/clients/client0/web1/web/admin/orders.php(0): acceptOrder(3, Array) #6 {main}`

**Comment by geniuskidkanyi** [comment]
Error fix by installing php soap, do you allow new contributors. i will like to contribute
